### ISSUE TITLE
[FEATURE TRACKING] Preparing and Enhancing Open Source Development

### ISSUE THREAD

**Issue by ganler** [ise-uiuc/nnsmith#33]
Before open-sourcing the nnsmith project, I want to simplify and standardize a bit the development and user accessibility. Below is a tracking list of TODOs for @ganler to make the repository a better open-source one in the next few months.

- [x] Setup `pre-commit`;
- [x] Setup `black` formatting (within pre-commit);
- Improve code quality and make NNSmith extensible.
    - [x] Sync with paper naming.
    - [x] Modularize data in abstract domain (`nnsmith/abstract`);
    - [x] Make model generation dependency-minimal and split it against model materialization;
    - [x] Make operator constraints extensible for other model formats;
    - [x] Refine backend runners to allow different model formats;
    - [x] Operator dialect;
    - [x] Add unit tests for serialization, op spec validity, etc.
    - [x] Hydra configuration;
    - [x] Fix dtype_test, fuzz and backend execution [X];
    - [x] Allow single-step fuzzing (currently we do multi-step fuzzing for the sake of coverage evaluation);
- [x] Setup Github CI; Thanks to @Co1lin!
- [x] Setup pip package;
