### ISSUE TITLE
[TRACKING] Follow-up Enhancements

### ISSUE THREAD

**Issue by ganler** [ise-uiuc/nnsmith#42]
The main features are refactored in https://github.com/ise-uiuc/nnsmith/issues/33 with a primary focus on extensibility, code quality, and maintainability (e.g., ci & PyPI). This thread tracks some follow-up (or P1~2) enhancements and features that we are going to work on in the next few weeks.

## 0.0.0

https://pypi.org/project/nnsmith/0.0.0/

- [x] Refactoring verbose printing with module-level loggers.  https://github.com/ise-uiuc/nnsmith/pull/44
- [x] Auto versioning https://github.com/ise-uiuc/nnsmith/pull/40
- [x] Dtype testing for model exportation; https://github.com/ise-uiuc/nnsmith/pull/40
- [x] Make `pygraphviz` an optional dependency as it requires system-level constraint https://github.com/ise-uiuc/nnsmith/pull/43

## 0.0.1 

https://pypi.org/project/nnsmith/0.0.1/

- [x] Stabilize `nnsmith.fuzz` via smoke testing in CI; https://github.com/ise-uiuc/nnsmith/pull/50
- [x] Fix core.Gemm; https://github.com/ise-uiuc/nnsmith/pull/45
- [x] Double-check and stabilize backend-oriented spec re-writing; https://github.com/ise-uiuc/nnsmith/pull/52
- [x] generation exception safety. https://github.com/ise-uiuc/nnsmith/pull/52
- [x] Well-form backend dispatching;
- [x] GitHub HEAD install (tested);
- [x] Fix XLA. https://github.com/ise-uiuc/nnsmith/pull/50 
- [x] Patchable bug filter. https://github.com/ise-uiuc/nnsmith/pull/53
- [x] Crash safety in execution; https://github.com/ise-uiuc/nnsmith/pull/54

## TBD

- Cleaning stale branches after a 5-month window size;
- [ ] `nnsmith.fuzz` TUI.
- [x] Implement exclude set logics;
- [ ] Replace `pygraphviz` with `graphviz` to release the dependency constraint by pygraphviz?
- [ ] Simplifying nnsmith arith by extending `z3.ArithRef`. https://github.com/Z3Prover/z3/issues/6309
- [ ] Well-form core operators and dialects; -- core operators should not change that frequently...
- [ ] Simplifying and bringing back attribute binning;
- [ ] CLI-level documentation;
- [ ] Tutorials on CLI, design, and extension.

**Comment by ganler** [comment]
Some new and main features/fixes that are not mentioned in the base comment, but will be served as the future release of `v0.1.0`:

GraphIR infrastructure for simplifying graph construction and mutation:
- https://github.com/ise-uiuc/nnsmith/pull/64
- https://github.com/ise-uiuc/nnsmith/pull/61

Scripts to evaluate coverage of generated tests:
- https://github.com/ise-uiuc/nnsmith/pull/60

Concolic generation, simplified size limiter, etc.
- https://github.com/ise-uiuc/nnsmith/pull/66

More backend support is coming soon.

**Comment by ganler** [comment]
Continued by tracking features via release versions or other smaller milestones.
